---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/forecasts":
    get:
      summary: list forecasts
      responses:
        '200':
          description: successful
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
